spring:
  rabbitmq:
    host: 192.168.200.130
    port: 5672
    username: admin
    password: 123
    #发布消息成功到交换器后会触发回调方法
    publisher-confirm-type: correlated
    #回退消息
    publisher-returns: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
